### PR TITLE
feat: trigger AsyncAPI site deploy

### PR DESCRIPTION
**Pull request by smoya**
**Description**

This PR adds a new step in the deploy.yml workflow so AsyncAPI website gets also deployed, updating the [roadmap](https://asyncapi.org/roadmap) if needed.

Note that `$NETLIFY_SITE_ID` env var has been renamed to `$NETLIFY_SHAPEUP_SITE_ID`, and `$NETLIFY_ASYNCAPI_SITE_ID` has been added. **Changes on secrets should be applied** cc @derberg

### CODE REVIEW

**Review by magicmatatjahu — COMMENTED** [review]
Do wee need two steps? I think that two curls in one step is enough :)

**Comment by smoya** [comment]
> Do wee need two steps? I think that two curls in one step is enough :)

Well they perform different actions so I would always advocate for having two separate curls, as they can give you a different response. One could work, the other fail so you only need to re-run the one that failed.

**Comment by derberg** [comment]
secrets added

> One could work, the other fail so you only need to re-run the one that failed.

you can rerun jobs but not steps afaik, so if you want to have such functionality then in the workflow file you need to have 2 independent jobs

anyway, separation of steps makes sense

**Review by magicmatatjahu — APPROVED** [review]
LGTM

**Comment by smoya** [comment]
> you can rerun jobs but not steps afaik, so if you want to have such functionality then in the workflow file you need to have 2 independent jobs

Yeah, totally right. Parallelism only happens at job level, which in this case I think it is not really needed.

**Pull request merged**
